version: 2.1

parameters:
  default-python-image:
    type: string
    default: "cimg/python:3.8"

executors:
  docker-amd64-image:
    parameters:
      python-image:
        type: string
        default: << pipeline.parameters.default-python-image >>
    docker:
      - image: << parameters.python-image >>
      - image: influxdb:3-core
        environment:
          - INFLUXDB3_NODE_IDENTIFIER_PREFIX=node01
          - INFLUXDB3_OBJECT_STORE=file
          - INFLUXDB3_DB_DIR=/var/lib/influxdb3/data
  docker-arm64-image:
    parameters:
      python-image:
        type: string
        default: << pipeline.parameters.default-python-image >>
    docker:
      - image: << parameters.python-image >>
      - image: influxdb:3-core
        environment:
          - INFLUXDB3_NODE_IDENTIFIER_PREFIX=node01
          - INFLUXDB3_OBJECT_STORE=file
          - INFLUXDB3_DB_DIR=/var/lib/influxdb3/data
    resource_class: arm.medium

commands:
  client-test:
    description: "Run tests"
    parameters:
      python-image:
        type: string
      pytest-marker:
        type: string
    steps:
      - restore_cache:
          name: Restoring Pip Cache
          keys:
            - &cache-key pip-cache-v11-<< parameters.python-image >>-{{ checksum "setup.py" }}
            - pip-cache-v11-<< parameters.python-image >>-
      - run:
          name: "Running tests"
          command: |
            python --version
            mkdir test-reports || true
            pip install . --user
            pip install .\[dataframe\] --user
            pip install .\[test\] --user
            pytest -m "<< parameters.pytest-marker >>" tests --junitxml=test-reports/junit.xml --cov=./influxdb_client_3 --cov-report xml:coverage.xml
      - save_cache:
          name: Saving Pip Cache
          key: *cache-key
          paths:
            - ".venv"
            - "~/.cache/pip"
            - "/usr/local/lib/site-python"
          when: always
  upload-codecov-amd64:
    steps:
      - run:
          name: Collecting coverage reports
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
            curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
            curl -s https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
            gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
            shasum -a 256 -c codecov.SHA256SUM
            chmod +x ./codecov
            ./codecov
  upload-codecov-arm64:
    steps:
      - run:
          name: Collecting coverage reports
          command: |
            curl -k https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
            curl -Os https://uploader.codecov.io/v0.8.0/aarch64/codecov
            curl -Os https://uploader.codecov.io/v0.8.0/aarch64/codecov.SHA256SUM
            curl -Os https://uploader.codecov.io/v0.8.0/aarch64/codecov.SHA256SUM.sig
            gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
            shasum -a 256 -c codecov.SHA256SUM
            sudo chmod +x codecov        

jobs:
  tests-python:
    parameters:
      python-image:
        type: string
        default: << pipeline.parameters.default-python-image >>
      exe:
        type: string
        default: docker-amd64-image
      pytest-marker:
        type: string
        default: "not integration"
    executor:
      name: << parameters.exe >>
      python-image: << parameters.python-image >>
    steps:
      - checkout
      - run:
          name: Setup InfluxDB service
          command: |
            ./scripts/influxdb-setup.sh \
              --export-url-as TESTING_INFLUXDB_URL \
              --export-db-as TESTING_INFLUXDB_DATABASE \
              --export-token-as TESTING_INFLUXDB_TOKEN
      - client-test:
          python-image: << parameters.python-image >>
          pytest-marker: << parameters.pytest-marker >>
      - store_test_results:
          path: test-reports
      - when:
          condition:
            equal: [ docker-amd64-image, << parameters.exe >> ]
          steps:
            - upload-codecov-amd64
      - when:
          condition:
            equal: [ docker-arm64-image, << parameters.exe >> ]
          steps:
            - upload-codecov-arm64
  check-code-style:
    docker:
      - image: << pipeline.parameters.default-python-image >>
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Checks style consistency of setup.py.
          command: |
            pip install flake8 --user
            flake8 setup.py
      - run:
          name: Checks style consistency across sources.
          command: |
            pip install flake8 --user
            flake8 influxdb_client_3/
      - run:
          name: Checks style consistency across tests.
          command: |
            pip install flake8 --user
            flake8 tests/
      - run:
          name: Checks style consistency across examples.
          command: |
            pip install flake8 --user
            flake8 Examples/
  check-twine:
    docker:
      - image: << pipeline.parameters.default-python-image >>
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Checks that the description will render correctly on PyPI.
          command: |
            pip install --upgrade pip
            pip install 'twine>=5.1,<6.1' --user
            python setup.py sdist bdist_wheel
            twine check dist/*
  check-docstyle:
    docker:
      - image: << pipeline.parameters.default-python-image >>
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Checks compliance with Python docstring convention.
          command: |
            pip install pydocstyle --user
            pydocstyle --count influxdb_client_3

workflows:
  version: 2
  build:
    jobs:
      - check-code-style
      #      - check-docstyle
      - check-twine
      - tests-python:
          matrix:
            parameters:
              exe: [ docker-amd64-image, docker-arm64-image ]
              python-image: [ << pipeline.parameters.default-python-image >>, "cimg/python:3.9", "cimg/python:3.10", "cimg/python:3.11", "cimg/python:3.12", cimg/python:3.13 ]
      - tests-python:
          requires:
            - tests-python
          name: test-integration
          python-image: << pipeline.parameters.default-python-image >>
          pytest-marker: "integration"
