version: 2.1

commands:
  client-test:
    description: "Run tests"
    parameters:
      python-image:
        type: string
      pytest-marker:
        type: string
    steps:
      - restore_cache:
          name: Restoring Pip Cache
          keys:
            - &cache-key pip-cache-v11-<< parameters.python-image >>-{{ checksum "setup.py" }}
            - pip-cache-v11-<< parameters.python-image >>-
      - run:
          name: "Running tests"
          command: |
            python --version
            mkdir test-reports || true
            pip install . --user
            pip install .\[dataframe\] --user
            pip install .\[test\] --user
            pytest -m "<< parameters.pytest-marker >>" tests --junitxml=test-reports/junit.xml --cov=./influxdb_client_3 --cov-report xml:coverage.xml
      - save_cache:
          name: Saving Pip Cache
          key: *cache-key
          paths:
            - ".venv"
            - "~/.cache/pip"
            - "/usr/local/lib/site-python"
          when: always
jobs:
  tests-vm:
    machine:
      image: ubuntu-2404:2024.11.1
    resource_class: arm.medium
    steps:
      - run: "apt update"
      - run: "apt -y upgrade"
      - run: "python3 -v"
workflows:
  version: 2
  build:
    jobs:
      - tests-vm
